# Generated by Django 6.0.4 on 2026-04-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeakEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('flow_in', models.FloatField()),
                ('flow_out', models.FloatField()),
                ('delta', models.FloatField()),
                ('duration_minutes', models.FloatField()),
                ('water_lost', models.FloatField()),
                ('money_lost', models.FloatField()),
                ('location', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
