# Generated by Django 6.0.4 on 2026-04-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leakevent',
            name='status',
            field=models.CharField(default='normal', max_length=20),
            preserve_default=False,
        ),
    ]
