# Generated by Django 6.0.4 on 2026-04-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alert_devicetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta_threshold', models.FloatField(default=5.0)),
                ('water_lost_threshold', models.FloatField(default=50.0)),
                ('duration_threshold', models.IntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
