# Generated by Django 6.0.4 on 2026-04-24 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('technician', 'Technician'), ('worker', 'Worker'), ('viewer', 'Viewer')], default='worker', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Used to know if a worker/technician can respond to alerts.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
