# Generated by Django 6.0.4 on 2026-04-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Indicates if a technician/worker can respond to alerts.'),
        ),
    ]
