# Generated by Django 6.0.4 on 2026-05-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Indicates if a technician can respond to leakage alerts.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('technician', 'Technician')], default='technician', max_length=20),
        ),
    ]
