from django.db import models


class LeakEvent(models.Model):
    """
    Stores confirmed leak events processed by the backend.
    This remains your history/incident model.
    """
    device_id = models.CharField(max_length=100)
    flow_in = models.FloatField()
    flow_out = models.FloatField()
    delta = models.FloatField()
    duration_minutes = models.FloatField()
    water_lost = models.FloatField()
    money_lost = models.FloatField()
    status = models.CharField(max_length=20)
    location = models.CharField(max_length=255)
    timestamp = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.device_id} - {self.location} - {self.timestamp}"


class Alert(models.Model):
    """
    Stores system alerts shown in the Flutter alerts screen.
    These are generated by backend logic when leak conditions occur.
    """
    SEVERITY_CHOICES = [
        ('info', 'Info'),
        ('warning', 'Warning'),
        ('critical', 'Critical'),
    ]

    device_id = models.CharField(max_length=100)
    title = models.CharField(max_length=255)
    message = models.TextField()
    location = models.CharField(max_length=255)
    severity = models.CharField(max_length=20, choices=SEVERITY_CHOICES)
    is_read = models.BooleanField(default=False)
    is_dismissed = models.BooleanField(default=False)
    timestamp = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.title} - {self.severity} - {self.location}"


class DeviceToken(models.Model):
    """
    Stores Firebase Cloud Messaging tokens for phones/devices.
    Django uses these tokens to send push notifications.
    """
    token = models.TextField(unique=True)
    device_id = models.CharField(max_length=100, blank=True, null=True)
    platform = models.CharField(max_length=20, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.device_id or 'unknown'} - {self.platform or 'unknown'}"


class AlertSettings(models.Model):
    """
    Stores the system-wide thresholds used by the backend
    when deciding warning, leak_detected, and critical states.
    """
    delta_threshold = models.FloatField(default=5.0)
    water_lost_threshold = models.FloatField(default=50.0)
    duration_threshold = models.IntegerField(default=10)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return (
            f"Thresholds(delta={self.delta_threshold}, "
            f"water_lost={self.water_lost_threshold}, "
            f"duration={self.duration_threshold})"
        )