from django.db import models
from django.contrib.auth.models import User


class LeakEvent(models.Model):
    """
    Stores confirmed leak events processed by the backend.
    This remains your history/incident model.
    """
    device_id = models.CharField(max_length=100)
    flow_in = models.FloatField()
    flow_out = models.FloatField()
    delta = models.FloatField()
    duration_minutes = models.FloatField()
    water_lost = models.FloatField()
    money_lost = models.FloatField()
    status = models.CharField(max_length=20)
    location = models.CharField(max_length=255)
    timestamp = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.device_id} - {self.location} - {self.timestamp}"


class Alert(models.Model):
    """
    Stores system alerts shown in the Flutter alerts screen.
    These are generated by backend logic when leak conditions occur.
    """
    SEVERITY_CHOICES = [
        ('info', 'Info'),
        ('warning', 'Warning'),
        ('critical', 'Critical'),
    ]

    device_id = models.CharField(max_length=100)
    title = models.CharField(max_length=255)
    message = models.TextField()
    location = models.CharField(max_length=255)
    severity = models.CharField(max_length=20, choices=SEVERITY_CHOICES)
    is_read = models.BooleanField(default=False)
    is_dismissed = models.BooleanField(default=False)
    timestamp = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.title} - {self.severity} - {self.location}"


class DeviceToken(models.Model):
    """
    Stores Firebase Cloud Messaging tokens for phones/devices.
    Django uses these tokens to send push notifications.
    """
    token = models.TextField(unique=True)
    device_id = models.CharField(max_length=100, blank=True, null=True)
    platform = models.CharField(max_length=20, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.device_id or 'unknown'} - {self.platform or 'unknown'}"


class AlertSettings(models.Model):
    """
    Stores the system-wide thresholds used by the backend
    when deciding warning, leak_detected, and critical states.
    """
    delta_threshold = models.FloatField(default=5.0)
    water_lost_threshold = models.FloatField(default=50.0)
    duration_threshold = models.IntegerField(default=10)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return (
            f"Thresholds(delta={self.delta_threshold}, "
            f"water_lost={self.water_lost_threshold}, "
            f"duration={self.duration_threshold})"
        )


class AlertResponse(models.Model):
    """
    Tracks who responded to an alert and what action they took.
    This allows the admin to see who acknowledged, responded to,
    resolved, or dismissed a notification.
    """
    ACTION_CHOICES = [
        ("acknowledged", "Acknowledged"),
        ("responding", "Responding"),
        ("resolved", "Resolved"),
        ("dismissed", "Dismissed"),
    ]

    alert = models.ForeignKey(
        Alert,
        on_delete=models.CASCADE,
        related_name="responses",
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="alert_responses",
    )
    action = models.CharField(max_length=20, choices=ACTION_CHOICES)
    notes = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.user.username} - {self.action} - {self.alert.title}"


class MaintenanceRequest(models.Model):
    """
    Tracks technician requests created from the app.
    This supports the Call Technician feature and gives the admin
    a history of maintenance/escalation actions.
    """
    STATUS_CHOICES = [
        ("pending", "Pending"),
        ("assigned", "Assigned"),
        ("in_progress", "In Progress"),
        ("completed", "Completed"),
    ]

    device_id = models.CharField(max_length=100)
    location = models.CharField(max_length=255)
    requested_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="maintenance_requests",
    )
    reason = models.TextField(default="Leak detected")
    severity = models.CharField(max_length=20, default="critical")
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default="pending",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.device_id} - {self.location} - {self.status}"